services:
  nginx:
    env_file:
      - .env
      - .production_env
    restart: unless-stopped

  api:
    image: ${DOCKER_REGISTRY_URL}/${BUILD_NAME}_build_api:${BUILD_TAG}
    env_file:
      - .env
      - .production_env
    environment:
      CONTAINER_VERSION: ${BUILD_TAG}
    secrets:
      - API_MASTER_KEY
      - POSTGRES_PASSWORD
      - POSTGRES_USER
      - JWT_KEY
      - JWT_KEY_PUB
    volumes:
      - api_log:/home/app/webapp/log
      - api_tmp:/home/app/webapp/tmp
    restart: unless-stopped
    tmpfs:
      - /pids:mode=7777,size=1k,uid=9999,gid=999

  auth:
    image: ${DOCKER_REGISTRY_URL}/${BUILD_NAME}_build_auth:${BUILD_TAG}
    env_file:
      - .env
      - .production_env
    environment:
      CONTAINER_VERSION: ${BUILD_TAG}
    secrets:
      - AUTH_MASTER_KEY
      - GOOGLE_CLIENT_ID
      - GOOGLE_CLIENT_SECRET
      - JWT_KEY
      - JWT_KEY_PUB
    volumes:
      - auth_log:/home/app/webapp/log
      - auth_tmp:/home/app/webapp/tmp
    restart: unless-stopped
    tmpfs:
      - /pids:mode=7777,size=1k,uid=9999,gid=999

  ui:
    image: ${DOCKER_REGISTRY_URL}/${BUILD_NAME}_build_ui:${BUILD_TAG}
    env_file:
      - .env
      - .production_env
    environment:
      CONTAINER_VERSION: ${BUILD_TAG}
    secrets:
      - UI_MASTER_KEY
      - JWT_KEY
      - JWT_KEY_PUB
    volumes:
      - ui_log:/home/app/webapp/log
      - ui_tmp:/home/app/webapp/tmp
    restart: unless-stopped
    tmpfs:
      - /pids:mode=7777,size=1k,uid=9999,gid=999

  worker:
    image: ${DOCKER_REGISTRY_URL}/${BUILD_NAME}_build_worker:${BUILD_TAG}
    env_file:
      - .env
      - .production_env
    environment:
      CONTAINER_VERSION: ${BUILD_TAG}
    secrets:
      - WORKER_MASTER_KEY
      - POSTGRES_PASSWORD
      - POSTGRES_USER
      - JWT_KEY
      - JWT_KEY_PUB
    volumes:
      - worker_log:/home/app/webapp/log
      - worker_tmp:/home/app/webapp/tmp
      - worker_storage:/app/storage
    restart: unless-stopped
    tmpfs:
      - /pids:mode=7777,size=1k,uid=9999,gid=999

  db:
    env_file:
      - .env
      - .production_env
    secrets:
      - POSTGRES_PASSWORD
      - POSTGRES_USER
    restart: unless-stopped

  adminer:
    env_file:
      - .env
      - .production_env

volumes:
  auth_log:
  auth_tmp:
  api_log:
  api_tmp:
  ui_log:
  ui_tmp:
  worker_log:
  worker_tmp:
  worker_storage:
